[package]
name = "raptorq"
description = "RaptorQ (RFC6330)"
license = "Apache-2.0"
version = "0.5.0"
authors = ["Christopher Berner <christopherberner@gmail.com>"]

[dependencies]
primal = "0.2"
petgraph = "0.4"
rand = "0.6"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "codec_benchmark"
harness = false

[[bin]]
name = "matrix_sparsity"
path = "src/bin_matrix_sparsity.rs"
test = false

[[bin]]
name = "encode_benchmark"
path = "src/bin_encode_benchmark.rs"
test = false

[profile.release]
debug = true
