[package]
name = "raptorq"
description = "RaptorQ (RFC6330)"
license = "Apache-2.0"
version = "0.6.0"
authors = ["Christopher Berner <christopherberner@gmail.com>"]

[dependencies]
primal = "0.2"
petgraph = "0.4"
rand = "0.6"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "codec_benchmark"
harness = false

[profile.release]
debug = true
