[package]
name = "raptorq"
description = "RaptorQ (RFC6330)"
license = "Apache-2.0"
version = "0.2.0"
authors = ["Christopher Berner <christopherberner@gmail.com>"]

[dependencies]
primal = "0.2"

[dev-dependencies]
criterion = "0.2"
rand = "0.6"

[[bench]]
name = "codec_benchmark"
harness = false

[[bin]]
name = "matrix_sparsity"
path = "src/bin_matrix_sparsity.rs"

[profile.release]
debug = true
